<<<<<<< HEAD
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: citiride_development

test:
  <<: *default
  database: citiride_test

production:
  <<: *default
  database: citiride_production
  username: citiride
  password: <%= ENV['CITIRIDE_DATABASE_PASSWORD'] %>
=======
test:
  adapter: postgresql
  encoding: unicode
  database: test-postgres_test
  pool: 5

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: test-postgres_production
#   pool: 5

development:
  adapter: postgresql
  database: test-postgres
  host: localhost
  pool: 5
  timeout: 5000
>>>>>>> 4f44b1da3e534122388c09e154ab5d4883c2c7a0
